#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# WebSSH Setup Script
# Run this once on the host server to configure and launch the application.
# Requirements: Docker, Docker Compose v2, OpenSSL, Node.js (for bcrypt hash)
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SSL_DIR="$REPO_ROOT/docker/nginx/ssl"
ENV_FILE="$REPO_ROOT/.env"

echo "========================================"
echo "  WebSSH Setup"
echo "========================================"
echo ""

# ── 1. Check dependencies ─────────────────────────────────────────────────────
for cmd in docker openssl node; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "ERROR: '$cmd' is required but not installed. Aborting."
    exit 1
  fi
done
if ! docker compose version &>/dev/null; then
  echo "ERROR: 'docker compose' (v2) is required but not found. Aborting."
  exit 1
fi

# ── 2. Collect configuration ──────────────────────────────────────────────────
echo "Please provide the following configuration values."
echo "(Press Enter to accept defaults where shown.)"
echo ""

read -rp "Server hostname [$(hostname)]: " SERVER_HOSTNAME
SERVER_HOSTNAME="${SERVER_HOSTNAME:-$(hostname)}"

read -rp "LDAP server host (e.g. ldap.example.com): " LDAP_HOST
read -rp "LDAP base DN (e.g. dc=example,dc=com): " LDAP_BASE_DN
read -rp "LDAP user DN template (use {username} as placeholder) [uid={username},ou=people,${LDAP_BASE_DN}]: " LDAP_USER_DN_TEMPLATE
LDAP_USER_DN_TEMPLATE="${LDAP_USER_DN_TEMPLATE:-uid={username},ou=people,${LDAP_BASE_DN}}"

read -rp "Path to LDAP CA certificate file (leave blank to skip): " LDAP_CA_SRC

read -rp "SSH host [host.docker.internal]: " SSH_HOST
SSH_HOST="${SSH_HOST:-host.docker.internal}"
read -rp "SSH port [22]: " SSH_PORT
SSH_PORT="${SSH_PORT:-22}"

read -rp "Admin username [admin]: " ADMIN_USERNAME
ADMIN_USERNAME="${ADMIN_USERNAME:-admin}"

while true; do
  read -rsp "Admin password: " ADMIN_PASS
  echo ""
  read -rsp "Confirm admin password: " ADMIN_PASS2
  echo ""
  if [ "$ADMIN_PASS" = "$ADMIN_PASS2" ]; then
    break
  fi
  echo "Passwords do not match. Please try again."
done

# ── 3. Generate bcrypt hash for admin password ────────────────────────────────
echo ""
echo "Generating admin password hash..."
ADMIN_PASSWORD_HASH=$(node -e "
const crypto = require('crypto');
// Use Node built-in crypto for a simple bcrypt-compatible approach via npm
// We call bcrypt via a one-liner if available, otherwise fall back to a note
try {
  const bcrypt = require('bcrypt');
  bcrypt.hash('${ADMIN_PASS}', 12).then(h => { process.stdout.write(h); process.exit(0); });
} catch(e) {
  // bcrypt not available globally; install it first
  process.stderr.write('bcrypt not found\n');
  process.exit(1);
}
" 2>/dev/null) || {
  echo "  bcrypt npm package not found. Installing temporarily..."
  npm install -g bcrypt --silent 2>/dev/null || true
  ADMIN_PASSWORD_HASH=$(node -e "
    const bcrypt = require('bcrypt');
    bcrypt.hash('${ADMIN_PASS}', 12).then(h => { process.stdout.write(h); process.exit(0); });
  ")
}
echo "  Admin password hash generated."

# ── 4. Generate JWT secret ────────────────────────────────────────────────────
JWT_SECRET=$(openssl rand -hex 64)
echo "  JWT secret generated."

# ── 5. Create SSL directory and generate self-signed certificate ──────────────
mkdir -p "$SSL_DIR"

echo ""
echo "Generating self-signed TLS certificate for '$SERVER_HOSTNAME'..."
openssl req -x509 -nodes -days 3650 -newkey rsa:4096 \
  -keyout "$SSL_DIR/server.key" \
  -out "$SSL_DIR/server.crt" \
  -subj "/CN=${SERVER_HOSTNAME}" \
  -addext "subjectAltName=DNS:${SERVER_HOSTNAME},IP:127.0.0.1" \
  2>/dev/null
echo "  Certificate saved to $SSL_DIR/server.crt"
echo "  Private key saved to $SSL_DIR/server.key"
chmod 600 "$SSL_DIR/server.key"

# ── 6. Copy LDAP CA certificate if provided ───────────────────────────────────
if [ -n "$LDAP_CA_SRC" ] && [ -f "$LDAP_CA_SRC" ]; then
  cp "$LDAP_CA_SRC" "$SSL_DIR/ldap-ca.crt"
  echo "  LDAP CA certificate copied to $SSL_DIR/ldap-ca.crt"
else
  touch "$SSL_DIR/ldap-ca.crt"
  echo "  WARNING: No LDAP CA certificate provided. LDAPS may fail certificate validation."
fi

# ── 7. Write .env file ────────────────────────────────────────────────────────
echo ""
echo "Writing .env configuration file..."
cat > "$ENV_FILE" <<EOF
# Generated by setup.sh on $(date)
SERVER_HOSTNAME=${SERVER_HOSTNAME}
JWT_SECRET=${JWT_SECRET}
ADMIN_USERNAME=${ADMIN_USERNAME}
ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}
LDAP_HOST=${LDAP_HOST}
LDAP_BASE_DN=${LDAP_BASE_DN}
LDAP_USER_DN_TEMPLATE=${LDAP_USER_DN_TEMPLATE}
LDAP_CA_CERT_PATH=/app/certs/ldap-ca.crt
SSH_HOST=${SSH_HOST}
SSH_PORT=${SSH_PORT}
REDIS_HOST=redis
REDIS_PORT=6379
XPRA_HOST=xpra
XPRA_PORT_START=10000
XPRA_PORT_END=11000
TLS_CERT_FILE=server.crt
TLS_KEY_FILE=server.key
NODE_ENV=production
EOF
echo "  .env written."

# ── 8. Build and start containers ─────────────────────────────────────────────
echo ""
echo "Building and starting Docker containers..."
cd "$REPO_ROOT"
docker compose build --no-cache
docker compose up -d

echo ""
echo "========================================"
echo "  WebSSH is now running!"
echo "  Open https://${SERVER_HOSTNAME} in your browser."
echo "  (Accept the self-signed certificate warning on first visit.)"
echo "========================================"
